feat: improve response error exception logs
Instead of just

!ENTRY org.eclipse.lsp4e 4 0 2025-12-17 09:07:40.931
!MESSAGE Internal error.

Produce an error that contains the internal error, such us

!ENTRY org.eclipse.lsp4e 4 0 2025-12-17 09:21:46.530
!MESSAGE Internal error.(-32603)
java.util.concurrent.CompletionException:
java.lang.NullPointerException: Cannot invoke
"org.eclipse.xtext.nodemodel.INode.getParent()" because "localNode" is
null
	... (abbreviated) ...
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke
"org.eclipse.xtext.nodemodel.INode.getParent()" because "localNode" is
null
	at org.eclipse.xtext.nodemodel.util.NodeModelUtils$Implementation.findLeafNodeAtOffset(NodeModelUtils.java:235)
	at org.eclipse.xtext.nodemodel.util.NodeModelUtils.findLeafNodeAtOffset(NodeModelUtils.java:74)
	... (abbreviated) ...